// Auto-generated by Inforact App Builder — DO NOT EDIT
"use server";

import {
  getRecords,
  getRecord,
  createRecord,
  updateRecord,
  deleteRecord,
  deleteRecords,
} from "@/lib/inforact-sdk";
import type { ListRecordsOptions } from "@/lib/inforact-sdk";

const TABLE_ID = "69d5fe3d355c2149339df5cf";

export interface AccountsReceivable {
  id: string;
  ARCode?: string;
  OrderId?: string;
  OrderCode?: string;
  CustomerId?: string;
  CustomerName?: string;
  InvoiceAmount?: number;
  PaidAmount?: number;
  Remaining?: number;
  DueDate?: string;
  /** Options: Chưa thu, Thu một phần, Quá hạn, Đã thu, Xóa nợ */
  Status?: string;
  CollectionNotes?: string;
  SaleOwner?: string;
  createdAt?: string;
  updatedAt?: string;
}

export type CreateAccountsReceivableInput = Omit<AccountsReceivable, "id" | "createdAt" | "updatedAt">;

export type UpdateAccountsReceivableInput = Partial<CreateAccountsReceivableInput>;

function mapRecord(record: any): AccountsReceivable {
  return {
    id: record.id,
    ...record.fields,
    createdAt: record.createdAt,
    updatedAt: record.updatedAt,
  };
}

export async function getAccountsReceivables(options?: ListRecordsOptions): Promise<{ data: AccountsReceivable[]; total: number }> {
  const result = await getRecords(TABLE_ID, options);
  return {
    data: result.records.map(mapRecord),
    total: result.total,
  };
}

export async function getAccountsReceivable(id: string): Promise<AccountsReceivable> {
  const record = await getRecord(TABLE_ID, id);
  return mapRecord(record);
}

export async function createAccountsReceivable(data: CreateAccountsReceivableInput): Promise<AccountsReceivable> {
  const record = await createRecord(TABLE_ID, data as Record<string, any>);
  return mapRecord(record);
}

export async function updateAccountsReceivable(id: string, data: UpdateAccountsReceivableInput): Promise<void> {
  await updateRecord(TABLE_ID, id, data as Record<string, any>);
}

export async function deleteAccountsReceivable(id: string): Promise<void> {
  await deleteRecord(TABLE_ID, id);
}

export async function deleteAccountsReceivables(ids: string[]): Promise<void> {
  await deleteRecords(TABLE_ID, ids);
}
